server:
  port:
spring:
  profiles:
    active: elapse_route
---
spring:
  profiles: add_request_header_route
  cloud:
    gateway:
      routes:
      - id: add_request_header_route
        uri: http://httpbin.org:80/get
        filters:
        - AddRequestHeader=X-Request-Foo, Bar
        predicates:
        - Method=GET

---
spring:
  profiles: add_request_parameter_route
  cloud:
    gateway:
      routes:
      - id: add_request_parameter_route
        uri: http://httpbin.org:80/get
        filters:
        - AddRequestParameter=foo, bar
        predicates:
        - Method=GET

---
spring:
  profiles: rewritepath_route
  cloud:
    gateway:
      routes:
        - id: rewritepath_route
          uri: http://httpbin.org
          predicates:
            - Path=/foo/**
          filters:
            - RewritePath=/foo/(?<segment>.*), /$\{segment}

---
spring:
  profiles: elapse_route
  cloud:
    gateway:
      routes:
        - id: elapse_route
          uri: http://httpbin.org:80/get
          filters:
          - Customer=true
          predicates:
          - Method=GET
